components:
  schemas:
    Error:
      properties:
        code:
          type: integer
        extensions:
          $ref: '#/components/schemas/Extensions'
        kind:
          type: string
        locations:
          items:
            $ref: '#/components/schemas/Location'
          type: array
        message:
          type: string
        name:
          type: string
        path:
          items:
            type: string
          type: array
        source:
          type: string
        tracing:
          $ref: '#/components/schemas/Tracing'
      required:
      - message
      - locations
      - path
      - extensions
      - code
      - kind
      - name
      - source
      - tracing
      type: object
    ErrorResponse:
      properties:
        errors:
          $ref: '#/components/schemas/Errors'
      required:
      - errors
      - data
      type: object
    Errors:
      items:
        $ref: '#/components/schemas/Error'
      type: array
    Extensions:
      properties:
        code:
          type: integer
        kind:
          type: string
        name:
          type: string
        source:
          type: string
        tracing:
          $ref: '#/components/schemas/Tracing'
      required:
      - name
      - source
      - code
      - kind
      - tracing
      type: object
    Location:
      properties:
        column:
          type: integer
        line:
          type: integer
      required:
      - line
      - column
      type: object
    Tracing:
      properties:
        trace_id:
          type: string
      required:
      - trace_id
      type: object
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths: {}
