components:
  schemas:
    TwitterTimeFormat:
      example: Sat Dec 31 23:59:59 +0000 2023
      pattern: ^(Sun|Mon|Tue|Wed|Thu|Fri|Sat) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)
        (0[1-9]|[12][0-9]|3[01]) (0[0-9]|1[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])
        ([+-][0-9]{4}) ([0-9]{4})$
      type: string
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths: {}
