components:
  schemas:
    InstructionType:
      enum:
      - TimelineAddEntries
      - TimelineClearCache
      - TimelinePinEntry
      - TimelineTerminateTimeline
      type: string
    InstructionUnion:
      discriminator:
        mapping":
          TimelineAddEntries: '#/components/schemas/TimelineAddEntries'
          TimelineClearCache: '#/components/schemas/TimelineClearCache'
          TimelinePinEntry: '#/components/schemas/TimelinePinEntry'
          TimelineTerminateTimeline: '#/components/schemas/TimelineTerminateTimeline'
        propertyName: type
      oneOf:
      - $ref: '#/components/schemas/TimelineAddEntries'
      - $ref: '#/components/schemas/TimelineClearCache'
      - $ref: '#/components/schemas/TimelinePinEntry'
      - $ref: '#/components/schemas/TimelineTerminateTimeline'
    TimelineAddEntries:
      properties:
        entries:
          items:
            $ref: '#/components/schemas/TimelineAddEntry'
          type: array
        type:
          $ref: '#/components/schemas/InstructionType'
          type: string
      required:
      - type
      - entries
    TimelineAddEntry:
      properties:
        content:
          $ref: ./content.yaml#/components/schemas/ContentUnion
        entryId:
          pattern: ^[a-z\-]+[0-9]+$
          type: string
        sortIndex:
          pattern: '[0-9]+$'
          type: string
      required:
      - content
      - entryId
      - sortIndex
    TimelineClearCache:
      properties:
        type:
          $ref: '#/components/schemas/InstructionType'
          type: string
      required:
      - type
    TimelinePinEntry:
      properties:
        entry:
          $ref: '#/components/schemas/TimelineAddEntry'
        type:
          $ref: '#/components/schemas/InstructionType'
          type: string
      required:
      - type
      - entry
    TimelineTerminateTimeline:
      properties:
        direction:
          enum:
          - Top
          - Bottom
          type: string
        type:
          $ref: '#/components/schemas/InstructionType'
          type: string
      required:
      - type
      - direction
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths: {}
