components:
  schemas:
    Timeline:
      properties:
        instructions:
          items:
            $ref: ./../schemas/instruction.yaml#/components/schemas/InstructionUnion
          type: array
        metadata:
          type: object
        responseObjects:
          type: object
      required:
      - instructions
    TimelineV2:
      properties:
        timeline:
          $ref: '#/components/schemas/Timeline'
      required:
      - timeline
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths: {}
