components:
  schemas:
    TypeName:
      enum:
      - TimelineTweet
      - TimelineTimelineItem
      - TimelineUser
      - TimelineTimelineCursor
      - TweetWithVisibilityResults
      - TimelineTimelineModule
      - Tweet
      - User
      type: string
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths: {}
