components:
  schemas:
    BookmarksResponse:
      properties:
        data:
          $ref: '#/components/schemas/BookmarksResponseData'
      required:
      - data
    BookmarksResponseData:
      properties:
        bookmark_timeline_v2:
          $ref: '#/components/schemas/BookmarksTimeline'
      required:
      - bookmark_timeline_v2
    BookmarksTimeline:
      properties:
        timeline:
          $ref: ./../schemas/timeline.yaml#/components/schemas/Timeline
      required:
      - timeline
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths:
  /graphql/tmd4ifV8RHltzn8ymGg1aw/Bookmarks:
    get:
      description: get bookmarks
      operationId: getBookmarks
      parameters:
      - content:
          application/json:
            required:
            - t
            - m
            - d
            - '4'
            - i
            - f
            - V
            - '8'
            - R
            - H
            - l
            - t
            - z
            - n
            - '8'
            - y
            - m
            - G
            - g
            - '1'
            - a
            - w
            schema:
              default: tmd4ifV8RHltzn8ymGg1aw
              example: tmd4ifV8RHltzn8ymGg1aw
              type: string
        in: query
        name: queryId
        required: true
      - content:
          application/json:
            required:
            - count
            - includePromotedContent
            schema:
              properties:
                count:
                  default: 20
                  example: 20
                  type: integer
                includePromotedContent:
                  default: true
                  example: true
                  type: boolean
              required:
              - count
              - includePromotedContent
              type: object
        in: query
        name: variables
        required: true
      - content:
          application/json:
            required:
            - graphql_timeline_v2_bookmark_timeline
            - blue_business_profile_image_shape_enabled
            - responsive_web_graphql_exclude_directive_enabled
            - verified_phone_label_enabled
            - responsive_web_graphql_timeline_navigation_enabled
            - responsive_web_graphql_skip_user_profile_image_extensions_enabled
            - tweetypie_unmention_optimization_enabled
            - vibe_api_enabled
            - responsive_web_edit_tweet_api_enabled
            - graphql_is_translatable_rweb_tweet_is_translatable_enabled
            - view_counts_everywhere_api_enabled
            - longform_notetweets_consumption_enabled
            - tweet_awards_web_tipping_enabled
            - freedom_of_speech_not_reach_fetch_enabled
            - standardized_nudges_misinfo
            - tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled
            - interactive_text_enabled
            - responsive_web_text_conversations_enabled
            - longform_notetweets_rich_text_read_enabled
            - responsive_web_enhance_cards_enabled
            schema:
              properties:
                blue_business_profile_image_shape_enabled:
                  default: true
                  example: true
                  type: boolean
                freedom_of_speech_not_reach_fetch_enabled:
                  default: false
                  example: false
                  type: boolean
                graphql_is_translatable_rweb_tweet_is_translatable_enabled:
                  default: true
                  example: true
                  type: boolean
                graphql_timeline_v2_bookmark_timeline:
                  default: true
                  example: true
                  type: boolean
                interactive_text_enabled:
                  default: true
                  example: true
                  type: boolean
                longform_notetweets_consumption_enabled:
                  default: true
                  example: true
                  type: boolean
                longform_notetweets_rich_text_read_enabled:
                  default: true
                  example: true
                  type: boolean
                responsive_web_edit_tweet_api_enabled:
                  default: true
                  example: true
                  type: boolean
                responsive_web_enhance_cards_enabled:
                  default: false
                  example: false
                  type: boolean
                responsive_web_graphql_exclude_directive_enabled:
                  default: true
                  example: true
                  type: boolean
                responsive_web_graphql_skip_user_profile_image_extensions_enabled:
                  default: false
                  example: false
                  type: boolean
                responsive_web_graphql_timeline_navigation_enabled:
                  default: true
                  example: true
                  type: boolean
                responsive_web_text_conversations_enabled:
                  default: false
                  example: false
                  type: boolean
                standardized_nudges_misinfo:
                  default: true
                  example: true
                  type: boolean
                tweet_awards_web_tipping_enabled:
                  default: false
                  example: false
                  type: boolean
                tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled:
                  default: false
                  example: false
                  type: boolean
                tweetypie_unmention_optimization_enabled:
                  default: true
                  example: true
                  type: boolean
                verified_phone_label_enabled:
                  default: false
                  example: false
                  type: boolean
                vibe_api_enabled:
                  default: true
                  example: true
                  type: boolean
                view_counts_everywhere_api_enabled:
                  default: true
                  example: true
                  type: boolean
              required:
              - graphql_timeline_v2_bookmark_timeline
              - blue_business_profile_image_shape_enabled
              - responsive_web_graphql_exclude_directive_enabled
              - verified_phone_label_enabled
              - responsive_web_graphql_timeline_navigation_enabled
              - responsive_web_graphql_skip_user_profile_image_extensions_enabled
              - tweetypie_unmention_optimization_enabled
              - vibe_api_enabled
              - responsive_web_edit_tweet_api_enabled
              - graphql_is_translatable_rweb_tweet_is_translatable_enabled
              - view_counts_everywhere_api_enabled
              - longform_notetweets_consumption_enabled
              - tweet_awards_web_tipping_enabled
              - freedom_of_speech_not_reach_fetch_enabled
              - standardized_nudges_misinfo
              - tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled
              - interactive_text_enabled
              - responsive_web_text_conversations_enabled
              - longform_notetweets_rich_text_read_enabled
              - responsive_web_enhance_cards_enabled
              type: object
        in: query
        name: features
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarksResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - tweet
