components:
  schemas:
    BookmarksResponse:
      properties:
        data:
          $ref: '#/components/schemas/BookmarksResponseData'
      required:
      - data
    BookmarksResponseData:
      properties:
        bookmark_timeline_v2:
          $ref: '#/components/schemas/BookmarksTimeline'
      required:
      - bookmark_timeline_v2
    BookmarksTimeline:
      properties:
        timeline:
          $ref: ./../schemas/timeline.yaml#/components/schemas/Timeline
      required:
      - timeline
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths:
  /tmd4ifV8RHltzn8ymGg1aw/Bookmarks:
    get:
      description: get bookmarks
      operationId: getBookmarks
      parameters:
      - in: query
        name: variables
        required: true
        schema:
          example: '{"count": 20, "includePromotedContent": true}'
          type: string
      - in: query
        name: features
        required: true
        schema:
          example: '{"graphql_timeline_v2_bookmark_timeline": true, "blue_business_profile_image_shape_enabled":
            true, "responsive_web_graphql_exclude_directive_enabled": true, "verified_phone_label_enabled":
            false, "responsive_web_graphql_timeline_navigation_enabled": true, "responsive_web_graphql_skip_user_profile_image_extensions_enabled":
            false, "tweetypie_unmention_optimization_enabled": true, "vibe_api_enabled":
            true, "responsive_web_edit_tweet_api_enabled": true, "graphql_is_translatable_rweb_tweet_is_translatable_enabled":
            true, "view_counts_everywhere_api_enabled": true, "longform_notetweets_consumption_enabled":
            true, "tweet_awards_web_tipping_enabled": false, "freedom_of_speech_not_reach_fetch_enabled":
            false, "standardized_nudges_misinfo": true, "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled":
            false, "interactive_text_enabled": true, "responsive_web_text_conversations_enabled":
            false, "longform_notetweets_rich_text_read_enabled": true, "responsive_web_enhance_cards_enabled":
            false}'
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: tmd4ifV8RHltzn8ymGg1aw
          example: tmd4ifV8RHltzn8ymGg1aw
          type: string
      - in: header
        name: authorization
        required: true
        schema:
          default: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA
          description: It is a constant value and does not need to be changed.
          type: string
      - in: header
        name: x-twitter-active-user
        required: true
        schema:
          default: 'yes'
          description: Unknown what this value means.
          type: string
      - in: header
        name: x-twitter-auth-type
        required: true
        schema:
          default: OAuth2Session
          description: Unknown what this value means.
          type: string
      - in: header
        name: x-twitter-client-language
        required: true
        schema:
          default: en
          description: language code.
          type: string
      - in: header
        name: user-agent
        required: true
        schema:
          default: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
            like Gecko) Chrome/112.0.0.0 Safari/537.36
          description: UserAgent, some APIs may be rejected if changed.
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarksResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-content-type-options:
              schema:
                type: string
            x-frame-options:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
            x-xss-protection:
              schema:
                type: integer
      tags:
      - Tweet
