components:
  schemas:
    FollowResponse:
      properties:
        data:
          $ref: '#/components/schemas/FollowResponseData'
      required:
      - data
    FollowResponseData:
      properties:
        user:
          $ref: '#/components/schemas/FollowResponseUser'
      required:
      - user
    FollowResponseResult:
      properties:
        __typename:
          $ref: ./../schemas/typename.yaml#/components/schemas/TypeName
        timeline:
          $ref: '#/components/schemas/FollowTimeline'
      required:
      - __typename
      - timeline
    FollowResponseUser:
      properties:
        result:
          $ref: '#/components/schemas/FollowResponseResult'
      required:
      - result
    FollowTimeline:
      properties:
        timeline:
          $ref: ./../schemas/timeline.yaml#/components/schemas/Timeline
      required:
      - timeline
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths:
  /IWP6Zt14sARO29lJT35bBw/Following:
    get:
      description: get user list of following
      operationId: getFollowing
      parameters:
      - in: query
        name: variables
        required: true
        schema:
          example: '{"userId": "44196397", "count": 20, "includePromotedContent":
            false}'
          type: string
      - in: query
        name: features
        required: true
        schema:
          example: '{"blue_business_profile_image_shape_enabled": true, "responsive_web_graphql_exclude_directive_enabled":
            true, "verified_phone_label_enabled": false, "responsive_web_graphql_timeline_navigation_enabled":
            true, "responsive_web_graphql_skip_user_profile_image_extensions_enabled":
            false, "tweetypie_unmention_optimization_enabled": true, "vibe_api_enabled":
            true, "responsive_web_edit_tweet_api_enabled": true, "graphql_is_translatable_rweb_tweet_is_translatable_enabled":
            true, "view_counts_everywhere_api_enabled": true, "longform_notetweets_consumption_enabled":
            true, "tweet_awards_web_tipping_enabled": false, "freedom_of_speech_not_reach_fetch_enabled":
            false, "standardized_nudges_misinfo": true, "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled":
            false, "interactive_text_enabled": true, "responsive_web_text_conversations_enabled":
            false, "longform_notetweets_rich_text_read_enabled": true, "responsive_web_enhance_cards_enabled":
            false}'
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: IWP6Zt14sARO29lJT35bBw
          example: IWP6Zt14sARO29lJT35bBw
          type: string
      - in: header
        name: authorization
        required: true
        schema:
          default: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA
          description: It is a constant value and does not need to be changed.
          type: string
      - in: header
        name: x-twitter-active-user
        required: true
        schema:
          default: 'yes'
          description: Unknown what this value means.
          type: string
      - in: header
        name: x-twitter-auth-type
        required: true
        schema:
          default: OAuth2Session
          description: Unknown what this value means.
          type: string
      - in: header
        name: x-twitter-client-language
        required: true
        schema:
          default: en
          description: language code.
          type: string
      - in: header
        name: user-agent
        required: true
        schema:
          default: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
            like Gecko) Chrome/112.0.0.0 Safari/537.36
          description: UserAgent, some APIs may be rejected if changed.
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-content-type-options:
              schema:
                type: string
            x-frame-options:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
            x-xss-protection:
              schema:
                type: integer
      tags:
      - UserList
  /djdTXDIk2qhd4OStqlUFeQ/Followers:
    get:
      description: get user list of followers
      operationId: getFollowers
      parameters:
      - in: query
        name: variables
        required: true
        schema:
          example: '{"userId": "44196397", "count": 20, "includePromotedContent":
            false}'
          type: string
      - in: query
        name: features
        required: true
        schema:
          example: '{"blue_business_profile_image_shape_enabled": true, "responsive_web_graphql_exclude_directive_enabled":
            true, "verified_phone_label_enabled": false, "responsive_web_graphql_timeline_navigation_enabled":
            true, "responsive_web_graphql_skip_user_profile_image_extensions_enabled":
            false, "tweetypie_unmention_optimization_enabled": true, "vibe_api_enabled":
            true, "responsive_web_edit_tweet_api_enabled": true, "graphql_is_translatable_rweb_tweet_is_translatable_enabled":
            true, "view_counts_everywhere_api_enabled": true, "longform_notetweets_consumption_enabled":
            true, "tweet_awards_web_tipping_enabled": false, "freedom_of_speech_not_reach_fetch_enabled":
            false, "standardized_nudges_misinfo": true, "tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled":
            false, "interactive_text_enabled": true, "responsive_web_text_conversations_enabled":
            false, "longform_notetweets_rich_text_read_enabled": true, "responsive_web_enhance_cards_enabled":
            false}'
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: djdTXDIk2qhd4OStqlUFeQ
          example: djdTXDIk2qhd4OStqlUFeQ
          type: string
      - in: header
        name: authorization
        required: true
        schema:
          default: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA
          description: It is a constant value and does not need to be changed.
          type: string
      - in: header
        name: x-twitter-active-user
        required: true
        schema:
          default: 'yes'
          description: Unknown what this value means.
          type: string
      - in: header
        name: x-twitter-auth-type
        required: true
        schema:
          default: OAuth2Session
          description: Unknown what this value means.
          type: string
      - in: header
        name: x-twitter-client-language
        required: true
        schema:
          default: en
          description: language code.
          type: string
      - in: header
        name: user-agent
        required: true
        schema:
          default: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
            like Gecko) Chrome/112.0.0.0 Safari/537.36
          description: UserAgent, some APIs may be rejected if changed.
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FollowResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-content-type-options:
              schema:
                type: string
            x-frame-options:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
            x-xss-protection:
              schema:
                type: integer
      tags:
      - UserList
