components:
  schemas:
    CommunitiesActions:
      properties:
        create:
          type: boolean
      required:
      - create
      type: object
    OneFactorLoginEligibility:
      properties:
        fetchStatus:
          type: string
      required:
      - fetchStatus
      type: object
    OtherResponse:
      properties:
        Session:
          $ref: '#/components/schemas/Session'
      type: object
    Session:
      properties:
        SsoInitTokens:
          type: object
        communitiesActions:
          $ref: '#/components/schemas/CommunitiesActions'
        country:
          pattern: ^[A-Z]{2}$
          type: string
        guestId:
          pattern: ^[0-9]+$
          type: string
        hasCommunityMemberships:
          type: boolean
        isActiveCreator:
          type: boolean
        isRestrictedSession:
          type: boolean
        isSuperFollowSubscriber:
          type: boolean
        language:
          pattern: ^[a-z]{2}$
          type: string
        oneFactorLoginEligibility:
          $ref: '#/components/schemas/OneFactorLoginEligibility'
        superFollowersCount:
          type: integer
        superFollowsApplicationStatus:
          type: string
        userFeatures:
          $ref: '#/components/schemas/UserFeatures'
        user_id:
          pattern: ^[0-9]+$
          type: string
      required:
      - country
      - communitiesActions
      - isActiveCreator
      - isRestrictedSession
      - guestId
      - hasCommunityMemberships
      - language
      - oneFactorLoginEligibility
      - ssoInitTokens
      - superFollowersCount
      - superFollowsApplicationStatus
      - user_id
      - userFeatures
      - isSuperFollowSubscriber
      type: object
    UserFeatures:
      properties:
        mediatool_studio_library:
          type: boolean
      required:
      - mediatool_studio_library
      type: object
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths:
  /other:
    get:
      description: This is not an actual endpoint
      operationId: other
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtherResponse'
          description: Successful operation
      tags:
      - other
