components:
  schemas:
    CreateRetweet:
      properties:
        result:
          $ref: '#/components/schemas/Retweet'
      required:
      - result
    CreateRetweetResponse:
      properties:
        data:
          $ref: '#/components/schemas/CreateRetweetResponseData'
      required:
      - data
    CreateRetweetResponseData:
      properties:
        create_retweet:
          $ref: '#/components/schemas/CreateRetweetResponseResult'
      required:
      - create_retweet
    CreateRetweetResponseResult:
      properties:
        retweet_results:
          $ref: '#/components/schemas/CreateRetweet'
      required:
      - retweet_results
    CreateTweet:
      properties:
        result:
          $ref: ./../schemas/tweet.yaml#/components/schemas/Tweet
      required:
      - result
    CreateTweetResponse:
      properties:
        data:
          $ref: '#/components/schemas/CreateTweetResponseData'
      required:
      - data
    CreateTweetResponseData:
      properties:
        create_tweet:
          $ref: '#/components/schemas/CreateTweetResponseResult'
      required:
      - create_tweet
    CreateTweetResponseResult:
      properties:
        tweet_results:
          $ref: '#/components/schemas/CreateTweet'
      required:
      - tweet_results
    DeleteRetweet:
      properties:
        result:
          items:
            $ref: '#/components/schemas/Retweet'
          type: object
      required:
      - result
    DeleteRetweetResponse:
      properties:
        data:
          $ref: '#/components/schemas/DeleteRetweetResponseData'
      required:
      - data
    DeleteRetweetResponseData:
      properties:
        create_retweet:
          $ref: '#/components/schemas/CreateRetweetResponseResult'
      required:
      - unretweet
    DeleteRetweetResponseResult:
      properties:
        retweet_results:
          $ref: '#/components/schemas/DeleteRetweet'
      required:
      - source_tweet_results
    DeleteTweetResponse:
      properties:
        data:
          $ref: '#/components/schemas/DeleteTweetResponseData'
      required:
      - data
    DeleteTweetResponseData:
      properties:
        delete_retweet:
          $ref: '#/components/schemas/DeleteTweetResponseResult'
      required:
      - delete_tweet
    DeleteTweetResponseResult:
      properties:
        tweet_results:
          type: object
      required:
      - tweet_results
    FavoriteTweet:
      properties:
        favorite_tweet:
          type: string
      required:
      - favorite_tweet
    FavoriteTweetResponseData:
      properties:
        data:
          $ref: '#/components/schemas/FavoriteTweet'
      required:
      - data
    Retweet:
      properties:
        legacy:
          properties:
            full_text:
              type: string
          required:
          - full_text
          type: object
        rest_id:
          pattern: ^[0-9]+$
          type: string
      required:
      - rest_id
      - legacy
    UnfavoriteTweet:
      properties:
        unfavorite_tweet:
          type: string
      required:
      - unfavorite_tweet
    UnfavoriteTweetResponseData:
      properties:
        data:
          $ref: '#/components/schemas/UnfavoriteTweet'
      required:
      - data
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths:
  /graphql/{pathQueryId}/CreateRetweet:
    post:
      description: create Retweet
      operationId: postCreateRetweet
      parameters:
      - in: path
        name: pathQueryId
        required: true
        schema:
          default: ojPdsZsimiJrUGLR1sjUtA
          example: ojPdsZsimiJrUGLR1sjUtA
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: ojPdsZsimiJrUGLR1sjUtA
          example: ojPdsZsimiJrUGLR1sjUtA
          type: string
      - in: query
        name: variables
        required: true
        schema:
          properties:
            dark_request:
              default: false
              example: false
              type: boolean
            tweet_id:
              default: '1349129669258448897'
              example: '1349129669258448897'
              type: string
          required:
          - tweet_id
          - dark_request
          type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRetweetResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - post
  /graphql/{pathQueryId}/CreateTweet:
    post:
      description: create Tweet
      operationId: postCreateTweet
      parameters:
      - in: path
        name: pathQueryId
        required: true
        schema:
          default: 1RyAhNwby-gzGCRVsMxKbQ
          example: 1RyAhNwby-gzGCRVsMxKbQ
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: 1RyAhNwby-gzGCRVsMxKbQ
          example: 1RyAhNwby-gzGCRVsMxKbQ
          type: string
      - in: query
        name: variables
        required: true
        schema:
          properties:
            dark_request:
              default: false
              example: false
              type: boolean
            media:
              properties:
                media_entities:
                  items:
                    type: object
                  type: array
                possibly_sensitive:
                  default: false
                  example: false
                  type: boolean
              required:
              - media_entities
              - possibly_sensitive
              type: object
            semantic_annotation_ids:
              items:
                type: object
              type: array
            tweet_text:
              default: test
              example: test
              type: string
          required:
          - tweet_text
          - media
          - semantic_annotation_ids
          - dark_request
          type: object
      - in: query
        name: features
        required: true
        schema:
          properties:
            blue_business_profile_image_shape_enabled:
              default: true
              example: true
              type: boolean
            freedom_of_speech_not_reach_fetch_enabled:
              default: true
              example: true
              type: boolean
            graphql_is_translatable_rweb_tweet_is_translatable_enabled:
              default: true
              example: true
              type: boolean
            interactive_text_enabled:
              default: true
              example: true
              type: boolean
            longform_notetweets_consumption_enabled:
              default: true
              example: true
              type: boolean
            longform_notetweets_rich_text_read_enabled:
              default: true
              example: true
              type: boolean
            responsive_web_edit_tweet_api_enabled:
              default: true
              example: true
              type: boolean
            responsive_web_enhance_cards_enabled:
              default: false
              example: false
              type: boolean
            responsive_web_graphql_exclude_directive_enabled:
              default: true
              example: true
              type: boolean
            responsive_web_graphql_skip_user_profile_image_extensions_enabled:
              default: false
              example: false
              type: boolean
            responsive_web_graphql_timeline_navigation_enabled:
              default: true
              example: true
              type: boolean
            responsive_web_text_conversations_enabled:
              default: false
              example: false
              type: boolean
            standardized_nudges_misinfo:
              default: true
              example: true
              type: boolean
            tweet_awards_web_tipping_enabled:
              default: false
              example: false
              type: boolean
            tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled:
              default: false
              example: false
              type: boolean
            tweetypie_unmention_optimization_enabled:
              default: true
              example: true
              type: boolean
            verified_phone_label_enabled:
              default: false
              example: false
              type: boolean
            vibe_api_enabled:
              default: true
              example: true
              type: boolean
            view_counts_everywhere_api_enabled:
              default: true
              example: true
              type: boolean
          required:
          - tweetypie_unmention_optimization_enabled
          - vibe_api_enabled
          - responsive_web_edit_tweet_api_enabled
          - graphql_is_translatable_rweb_tweet_is_translatable_enabled
          - view_counts_everywhere_api_enabled
          - longform_notetweets_consumption_enabled
          - tweet_awards_web_tipping_enabled
          - interactive_text_enabled
          - responsive_web_text_conversations_enabled
          - longform_notetweets_rich_text_read_enabled
          - blue_business_profile_image_shape_enabled
          - responsive_web_graphql_exclude_directive_enabled
          - verified_phone_label_enabled
          - freedom_of_speech_not_reach_fetch_enabled
          - standardized_nudges_misinfo
          - tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled
          - responsive_web_graphql_skip_user_profile_image_extensions_enabled
          - responsive_web_graphql_timeline_navigation_enabled
          - responsive_web_enhance_cards_enabled
          type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTweetResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - post
  /graphql/{pathQueryId}/DeleteRetweet:
    post:
      description: delete Retweet
      operationId: postDeleteRetweet
      parameters:
      - in: path
        name: pathQueryId
        required: true
        schema:
          default: iQtK4dl5hBmXewYZuEOKVw
          example: iQtK4dl5hBmXewYZuEOKVw
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: iQtK4dl5hBmXewYZuEOKVw
          example: iQtK4dl5hBmXewYZuEOKVw
          type: string
      - in: query
        name: variables
        required: true
        schema:
          properties:
            dark_request:
              default: false
              example: false
              type: boolean
            source_tweet_id:
              default: '1349129669258448897'
              example: '1349129669258448897'
              type: string
          required:
          - source_tweet_id
          - dark_request
          type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteRetweetResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - post
  /graphql/{pathQueryId}/DeleteTweet:
    post:
      description: delete Retweet
      operationId: postDeleteTweet
      parameters:
      - in: path
        name: pathQueryId
        required: true
        schema:
          default: VaenaVgh5q5ih7kvyVjgtg
          example: VaenaVgh5q5ih7kvyVjgtg
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: VaenaVgh5q5ih7kvyVjgtg
          example: VaenaVgh5q5ih7kvyVjgtg
          type: string
      - in: query
        name: variables
        required: true
        schema:
          properties:
            dark_request:
              default: false
              example: false
              type: boolean
            tweet_id:
              default: '1349129669258448897'
              example: '1349129669258448897'
              type: string
          required:
          - tweet_id
          - dark_request
          type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteTweetResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - post
  /graphql/{pathQueryId}/FavoriteTweet:
    post:
      description: favorite Tweet
      operationId: postFavoriteTweet
      parameters:
      - in: path
        name: pathQueryId
        required: true
        schema:
          default: lI07N6Otwv1PhnEgXILM7A
          example: lI07N6Otwv1PhnEgXILM7A
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: lI07N6Otwv1PhnEgXILM7A
          example: lI07N6Otwv1PhnEgXILM7A
          type: string
      - in: query
        name: variables
        required: true
        schema:
          properties:
            dark_request:
              default: false
              example: false
              type: boolean
            tweet_id:
              default: '1349129669258448897'
              example: '1349129669258448897'
              type: string
          required:
          - tweet_id
          - dark_request
          type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoriteTweetResponseData'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - post
  /graphql/{pathQueryId}/UnfavoriteTweet:
    post:
      description: unfavorite Tweet
      operationId: postUnfavoriteTweet
      parameters:
      - in: path
        name: pathQueryId
        required: true
        schema:
          default: ZYKSe-w7KEslx3JhSIk5LA
          example: ZYKSe-w7KEslx3JhSIk5LA
          type: string
      - in: query
        name: queryId
        required: true
        schema:
          default: ZYKSe-w7KEslx3JhSIk5LA
          example: ZYKSe-w7KEslx3JhSIk5LA
          type: string
      - in: query
        name: variables
        required: true
        schema:
          properties:
            dark_request:
              default: false
              example: false
              type: boolean
            tweet_id:
              default: '1349129669258448897'
              example: '1349129669258448897'
              type: string
          required:
          - tweet_id
          - dark_request
          type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnfavoriteTweetResponseData'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - post
