components:
  schemas:
    ProfileResponse:
      properties:
        data:
          $ref: '#/components/schemas/ProfileResponseData'
      required:
      - data
    ProfileResponseData:
      properties:
        user_result_by_screen_name:
          $ref: '#/components/schemas/UserResultByScreenName'
      required:
      - user_result_by_screen_name
    UserResultByScreenName:
      properties:
        id:
          pattern: ^[0-9a-zA-Z]+$
          type: string
        result:
          $ref: '#/components/schemas/UserResultByScreenNameResult'
      required:
      - id
      - result
    UserResultByScreenNameLegacy:
      properties:
        blocked_by:
          type: boolean
        blocking:
          type: boolean
        followed_by:
          type: boolean
        following:
          type: boolean
        name:
          type: string
        protected:
          type: boolean
        screen_name:
          type: string
    UserResultByScreenNameResult:
      properties:
        __typename:
          $ref: ./../schemas/typename.yaml#/components/schemas/TypeName
        id:
          pattern: ^[0-9a-zA-Z=]+$
          type: string
        legacy:
          $ref: '#/components/schemas/UserResultByScreenNameLegacy'
        profilemodules:
          type: object
        rest_id:
          pattern: ^[0-9]+$
          type: string
      required:
      - __typename
      - id
      - legacy
      - profilemodules
      - rest_id
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths:
  /9zwVLJ48lmVUk8u_Gh9DmA/ProfileSpotlightsQuery:
    get:
      description: get user by screen name
      operationId: getProfileSpotlightsQuery
      parameters:
      - in: query
        name: queryId
        required: true
        schema:
          default: 9zwVLJ48lmVUk8u_Gh9DmA
          example: 9zwVLJ48lmVUk8u_Gh9DmA
          type: string
      - content:
          application/json:
            schema:
              properties:
                screen_name:
                  default: elonmusk
                  example: elonmusk
                  type: string
              required:
              - screen_name
              type: object
        in: query
        name: variables
        required: true
      - content:
          application/json:
            schema:
              properties: {}
              required: []
              type: object
        in: query
        name: features
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-content-type-options:
              schema:
                type: string
            x-frame-options:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
            x-xss-protection:
              schema:
                type: integer
