components:
  schemas:
    UserResponse:
      properties:
        data:
          $ref: '#/components/schemas/UserResponseData'
      required:
      - data
    UserResponseData:
      properties:
        user:
          $ref: ./../schemas/user.yaml#/components/schemas/UserResults
      required:
      - user
info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths:
  /graphql/sLVLhk0bGj3MVFEKTdax1w/UserByScreenName:
    get:
      description: get user by screen name
      operationId: getUserByScreenName
      parameters:
      - content:
          application/json:
            schema:
              default: sLVLhk0bGj3MVFEKTdax1w
              example: sLVLhk0bGj3MVFEKTdax1w
              type: string
        in: query
        name: queryId
        required: true
      - content:
          application/json:
            schema:
              properties:
                screen_name:
                  default: elonmusk
                  example: elonmusk
                  type: string
                withSafetyModeUserFields:
                  default: true
                  example: true
                  type: boolean
              required:
              - screen_name
              - withSafetyModeUserFields
              type: object
        in: query
        name: variables
        required: true
      - content:
          application/json:
            schema:
              properties:
                blue_business_profile_image_shape_enabled:
                  default: true
                  example: true
                  type: boolean
                responsive_web_graphql_exclude_directive_enabled:
                  default: true
                  example: true
                  type: boolean
                responsive_web_graphql_skip_user_profile_image_extensions_enabled:
                  default: false
                  example: false
                  type: boolean
                responsive_web_graphql_timeline_navigation_enabled:
                  default: true
                  example: true
                  type: boolean
                verified_phone_label_enabled:
                  default: false
                  example: false
                  type: boolean
              required:
              - blue_business_profile_image_shape_enabled
              - responsive_web_graphql_exclude_directive_enabled
              - verified_phone_label_enabled
              - responsive_web_graphql_skip_user_profile_image_extensions_enabled
              - responsive_web_graphql_timeline_navigation_enabled
              type: object
        in: query
        name: features
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
          description: Successful operation
          headers:
            x-connection-hash:
              schema:
                type: string
            x-rate-limit-limit:
              schema:
                type: integer
            x-rate-limit-remaining:
              schema:
                type: integer
            x-rate-limit-reset:
              schema:
                type: integer
            x-response-time:
              schema:
                type: integer
            x-tfe-preserve-body:
              schema:
                type: boolean
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - user
