info:
  title: Twitter OpenAPI
  version: 0.0.1
openapi: 3.0.3
paths:
  /1.1/friendships/create.json:
    post:
      description: post create friendships
      operationId: postCreateFriendships
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                include_blocked_by:
                  default: 1
                  example: 1
                  type: integer
                include_blocking:
                  default: 1
                  example: 1
                  type: integer
                include_can_dm:
                  default: 1
                  example: 1
                  type: integer
                include_can_media_tag:
                  default: 1
                  example: 1
                  type: integer
                include_ext_has_nft_avatar:
                  default: 1
                  example: 1
                  type: integer
                include_ext_is_blue_verified:
                  default: 1
                  example: 1
                  type: integer
                include_ext_profile_image_shape:
                  default: 1
                  example: 1
                  type: integer
                include_ext_verified_type:
                  default: 1
                  example: 1
                  type: integer
                include_followed_by:
                  default: 1
                  example: 1
                  type: integer
                include_mute_edge:
                  default: 1
                  example: 1
                  type: integer
                include_profile_interstitial_type:
                  default: 1
                  example: 1
                  type: integer
                include_want_retweets:
                  default: 1
                  example: 1
                  type: integer
                skip_status:
                  default: 1
                  example: 1
                  type: integer
                user_id:
                  default: '44196397'
                  example: '44196397'
                  type: string
              required:
              - include_profile_interstitial_type
              - include_blocking
              - include_blocked_by
              - include_followed_by
              - include_want_retweets
              - include_mute_edge
              - include_can_dm
              - include_can_media_tag
              - include_ext_has_nft_avatar
              - include_ext_is_blue_verified
              - include_ext_verified_type
              - include_ext_profile_image_shape
              - skip_status
              - user_id
        description: body
        required: true
      responses:
        '200':
          description: Successful operation
          headers:
            status:
              schema:
                type: string
            x-access-level:
              schema:
                type: string
            x-client-event-enabled:
              schema:
                type: boolean
            x-connection-hash:
              schema:
                type: string
            x-content-type-options:
              schema:
                type: string
            x-response-time:
              schema:
                type: integer
            x-transaction:
              schema:
                type: string
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - v1.1-post
  /1.1/friendships/destroy.json:
    post:
      description: post destroy friendships
      operationId: postDestroyFriendships
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                include_blocked_by:
                  default: 1
                  example: 1
                  type: integer
                include_blocking:
                  default: 1
                  example: 1
                  type: integer
                include_can_dm:
                  default: 1
                  example: 1
                  type: integer
                include_can_media_tag:
                  default: 1
                  example: 1
                  type: integer
                include_ext_has_nft_avatar:
                  default: 1
                  example: 1
                  type: integer
                include_ext_is_blue_verified:
                  default: 1
                  example: 1
                  type: integer
                include_ext_profile_image_shape:
                  default: 1
                  example: 1
                  type: integer
                include_ext_verified_type:
                  default: 1
                  example: 1
                  type: integer
                include_followed_by:
                  default: 1
                  example: 1
                  type: integer
                include_mute_edge:
                  default: 1
                  example: 1
                  type: integer
                include_profile_interstitial_type:
                  default: 1
                  example: 1
                  type: integer
                include_want_retweets:
                  default: 1
                  example: 1
                  type: integer
                skip_status:
                  default: 1
                  example: 1
                  type: integer
                user_id:
                  default: '44196397'
                  example: '44196397'
                  type: string
              required:
              - include_profile_interstitial_type
              - include_blocking
              - include_blocked_by
              - include_followed_by
              - include_want_retweets
              - include_mute_edge
              - include_can_dm
              - include_can_media_tag
              - include_ext_has_nft_avatar
              - include_ext_is_blue_verified
              - include_ext_verified_type
              - include_ext_profile_image_shape
              - skip_status
              - user_id
        description: body
        required: true
      responses:
        '200':
          description: Successful operation
          headers:
            status:
              schema:
                type: string
            x-access-level:
              schema:
                type: string
            x-client-event-enabled:
              schema:
                type: boolean
            x-connection-hash:
              schema:
                type: string
            x-content-type-options:
              schema:
                type: string
            x-response-time:
              schema:
                type: integer
            x-transaction:
              schema:
                type: string
            x-transaction-id:
              schema:
                type: string
            x-twitter-response-tags:
              schema:
                type: string
      tags:
      - v1.1-post
